USE `family-relations`;

-- Family Table
DROP TABLE IF EXISTS Family;
CREATE TABLE Family(pid INT PRIMARY KEY REFERENCES Persons(Id), fid INT REFERENCES Persons(Id), mid INT REFERENCES Persons(Id));

-- Insert Info Into Family Table
-- Family 1 - My Family
INSERT INTO FAMILY VALUES(1, 4, 5);
INSERT INTO FAMILY VALUES(2, 4, 5);
INSERT INTO FAMILY VALUES(3, 4, 5);
-- Family 2 - Cousins From Mother's side -
INSERT INTO FAMILY VALUES(6, 10, 11);
INSERT INTO FAMILY VALUES(7, 10, 11);
INSERT INTO FAMILY VALUES(8, 10, 11);
INSERT INTO FAMILY VALUES(9, 10, 11);
-- Family 3 - Cousins From Father's side
INSERT INTO FAMILY VALUES(12, 16, 17);
INSERT INTO FAMILY VALUES(13, 16, 17);
INSERT INTO FAMILY VALUES(14, 16, 17);
INSERT INTO FAMILY VALUES(15, 16, 17);
-- Family 4 - Mother's Parents
INSERT INTO FAMILY VALUES(5, 18, 19);
INSERT INTO FAMILY VALUES(11, 18, 19);
INSERT INTO FAMILY VALUES(17, 18, 19);
-- Family 5 - Father's Parents
INSERT INTO FAMILY VALUES(4, 20, 21);
INSERT INTO FAMILY VALUES(10, 20, 21);
INSERT INTO FAMILY VALUES(16, 20, 21);

-- View All In Family Table
SELECT * FROM FAMILY;